modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All-Rights-Reserved"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "MUKSC"
description = '''
'''

[[dependencies."${id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "tacz"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"
