modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/MUKSC/TaCZTweaks/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://modrinth.com/mod/tacz-tweaks"
logoFile = "icon.png"
authors = "MUKSC"
description = '''
A collection of random tweaks and features to enhance my experience with TaCZ.'''

[[dependencies."${id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "tacz"
mandatory = true
versionRange = "${tacz_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${id}"]]
modId = "kotlinforforge"
mandatory = true
versionRange = "${kotlinforforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "${yacl_version_range}"
ordering = "NONE"
side = "BOTH"
