java.version=21
minecraft.version=1.21.1

version.target.min=1.1.8
version.target.max=1.1.9

libs.parchment=2024.11.17
libs.kff=5.11.0
libs.yacl=3.8.2+1.21.1-neoforge
libs.tacz=1.1.8-r2

libs.lso=1.21.1-2.4.2
libs.sable=1.0.6
libs.lr-tactical=0.3.0
libs.sound-physics-remastered=neoforge-1.21.1-1.5.1

libs.better-modlist=1.1.21
# 3.0.0+1.21
libs.cubes-without-borders=epixUL1j