java.version=17
minecraft.version=1.20.1

version.target.min=1.1.8
version.target.max=1.1.9

libs.parchment=2023.09.03
libs.mixin=0.8.5
libs.kff=4.12.0
libs.yacl=3.6.6+1.20.1-forge
libs.tacz=1.1.8

libs.firstaid=1.20.1-1.1
libs.lso=1.20.1-2.4.2
# 1.20.1-forge-3.2.0
libs.pillagers-gun=7667398
libs.valkyrienskies=2.4.10
libs.valkyrienskies-core=1.1.0+1d4a7373e9
libs.lr-tactical=0.4.1
libs.sound-physics-remastered=forge-1.20.1-1.5.1

libs.better-modlist=0.1.15
# 3.0.0+1.20
libs.cubes-without-borders=QzVMYIfG